### ISSUE TITLE
How get now enviromentin code?

### ISSUE THREAD

**Issue by kkak10** [frank-weindel/webpack-config-loader#1]
How get now enviroment in code?

**Comment by frank-weindel** [comment]
Currently you'll have to just add the environment name to each individual config. This could be a feature though if you want to create a PR

**Comment by kkak10** [comment]
Thank you! I Will be create PR.

I use this lib many useful. :)

**Comment by kkak10** [comment]
@frank-weindel 
I developed this feature and registered it as PR.

**Comment by kkak10** [comment]
close.
